// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

package client

import (
	context "context"
	models "github.com/Clever/resolve-ip/gen-go/models"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockClient) EXPECT() *MockClientMockRecorder {
	return _m.recorder
}

// HealthCheck mocks base method
func (_m *MockClient) HealthCheck(ctx context.Context) error {
	ret := _m.ctrl.Call(_m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck
func (_mr *MockClientMockRecorder) HealthCheck(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "HealthCheck", arg0)
}

// LocationForIP mocks base method
func (_m *MockClient) LocationForIP(ctx context.Context, ip string) (*models.IP, error) {
	ret := _m.ctrl.Call(_m, "LocationForIP", ctx, ip)
	ret0, _ := ret[0].(*models.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LocationForIP indicates an expected call of LocationForIP
func (_mr *MockClientMockRecorder) LocationForIP(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LocationForIP", arg0, arg1)
}
