image: clever/drone-go:1.7
notify:
  email:
    recipients:
    - drone@clever.com
publish:
  catapult:
    url: $$catapult_url
    application: resolve-ip
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/resolve-ip
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
  npm:
    email: $$npm_drone_email
    folder: gen-js/
    password: $$npm_drone_password
    registry: https://registry.npmjs.org
    username: $$npm_drone_username
    when:
      branch: master
script:
- tar xvzf GeoLiteCity_20160301.tar.gz
- make install_deps
- make test
- make build
