
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Clever/discovery-go"
  version = "1.5.0"

[[constraint]]
  name = "github.com/Clever/go-process-metrics"

[[constraint]]
  name = "github.com/afex/hystrix-go"

[[constraint]]
  name = "github.com/donovanhide/eventsource"

[[constraint]]
  name = "github.com/go-errors/errors"

[[constraint]]
  name = "github.com/go-openapi/errors"

[[constraint]]
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  name = "github.com/go-openapi/swag"

[[constraint]]
  name = "github.com/go-openapi/validate"

[[constraint]]
  branch = "master"
  name = "github.com/golang/mock"

[[constraint]]
  name = "github.com/gorilla/mux"

[[constraint]]
  name = "github.com/kardianos/osext"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v5"
  version = "5.1.0"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"

[[constraint]]
  name = "gopkg.in/Clever/optimus.v3"
  version = "3.7.0"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"
  version = "1.2.13"
