swagger: '2.0'
info:
  title: resolve-ip
  description: service that takes in an IP address and converts it to a latitude and longitude
  # when changing the version here, make sure to
  # 1. re-run `make generate` to generate clients and server
  # 2. commit the new clients, and tag the commit with the version:
  #    git tag -a vX.Y.Z -m "vX.Y.Z"
  #    git push origin --tags
  version: 4.1.0
  x-npm-package: resolve-ip
schemes:
  - http
produces:
  - application/json
responses:
  BadRequest:
    description: "Bad Request"
    schema:
      $ref: "#/definitions/BadRequest"
  InternalError:
    description: "Internal Error"
    schema:
      $ref: "#/definitions/InternalError"
paths:
  /healthcheck:
    get:
      operationId: healthCheck
      description: Checks if the service is healthy
      responses:
        200:
          description: OK response
  /ip/{ip}:
    get:
      operationId: locationForIP
      description: Gets the lat/lon for a given IP.
      parameters:
        - name: ip
          in: path
          description: The IP to try to locate
          required: true
          type: string
      responses:
        200:
          description: Successfully found a location for the given IP
          schema:
            $ref: '#/definitions/IP'
        404:
          description: Was not able to determine the location for the given IP
          schema:
            $ref: '#/definitions/NotFound'
definitions:
  IP:
    type: object
    properties:
      lat:
        type: number
      lon:
        type: number
    required:
      - lat
      - lon
  InternalError:
    type: object
    properties:
      message:
        type: string
  BadRequest:
    type: object
    properties:
      message:
        type: string
  NotFound:
    type: object
    properties:
      message:
        type: string
